<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="aspire984" name="com.projectname.test.functional.modulename2.SearchByName" tests="1" failures="1" timestamp="12 Dec 2014 09:14:24 GMT" time="46.616" errors="0">
  <testcase name="searchbyname" time="46.616" classname="com.projectname.test.functional.modulename2.SearchByName">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.projectname.testutils.genericutility.ExceptionHandler.<init>(ExceptionHandler.java:31)
	at com.projectname.testutils.seleniumutils.SeleniumWebDriver.waitForPageToLoad(SeleniumWebDriver.java:301)
	at com.projectname.testutils.pages.LoginPage.login(LoginPage.java:30)
	at com.projectname.test.functional.modulename2.SearchByName.searchbyname(SearchByName.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- searchbyname -->
</testsuite> <!-- com.projectname.test.functional.modulename2.SearchByName -->
